Omit unnecessary libraries for web
firebase/flutterfire pull request #10068
Opened 2022-12-07 10:41 UTC by kaptnkoala

## Description

Currently it seems that unnecessary web libraries are loaded on start of a Flutter Web application. 

In our case, we only want to use Firebase Analytics to send tracking data. For this we need to install the firebase_core and firebase_analytics package as dependencies in our project. But when we launch the bundled app in the browser, there are additional JS libraries loaded to the expected `firebase-app.js` and `firebase-analytics.js` files. At launch of our app, the firebase files are loaded.

- firebase-app.js
- firebase-analytics.js
- firebase-app-check.js
- firebase-remote-config.js
- firebase-firestore.js

The `firebase-firestore.js`dependency comes from the firebase_case and firebase_analytics using shared functionality from _flutterfire_internals, which has the `cloud_firestore_platform_interface` and `cloud_firestore_web` packages in its dependencies. But there does not seem to be any code used from these dependencies, so they can be just removed.

The `firebase-app-check.js` and `firebase-remote-config.js` libraries because the app-check and remote-config are installed as default web services in FirebaseCoreWeb platform interface. I have not found any explanation in the code, why this is necessary, because both web plugins register the web service themselves, when they get added as dependency to a project.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-01-30 12:38 UTC, russellwheatley requested changes

2023-01-30 12:38 UTC, russellwheatley commented on packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
> -    'app-check': FirebaseWebService._('app-check', override: 'app_check'),
This isn't going to work. We still need to rename those libraries, just not add them as a dependency.

2023-04-25 15:00 UTC, russellwheatley commented
Hey @kaptnkoala - do you intend to update this PR?

2023-06-07 12:19 UTC, blaugold commented
@russellwheatley I've update the PR so that web plugins that need override the Firebase Web product name, provide the override when registering them selfs. I felt like that is a more natural place to define those overrides, but let me know what you think.

The necessary change in the `firebase_web_core` is breaking though.

2023-06-08 09:04 UTC, russellwheatley commented
Thanks @blaugold! This is exactly what was needed. We don't consider this breaking as it is underlying implementation and not user facing API 😄

2023-06-08 09:04 UTC, russellwheatley approved these changes

2023-06-12 11:01 UTC, russellwheatley commented
@blaugold - do you mind merging with `master`? I think it'll fix the Firestore web e2e tests

2023-06-12 11:57 UTC, blaugold commented
@russellwheatley Thanks for the ping. I think that did it.

2023-06-12 14:26 UTC, merged