new(firebase_auth_ui): added Hungarian localization
firebase/flutterfire pull request #10111
Opened 2022-12-14 11:00 UTC by koltai75

## Description

Added Hungarian localization to Firebase Auth UI.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

2022-12-14 14:56 UTC, lesnitsky approved these changes

2022-12-15 09:54 UTC, koltai75 commented
@lesnitsky I also found out that some labels are hardcoded, for example [here](https://github.com/firebase/flutterfire/blob/dd611cd25139f78bc947a68366213902a31ae350/packages/firebase_ui_auth/lib/src/screens/email_verification_screen.dart#L178) and [here](https://github.com/firebase/flutterfire/blob/dd611cd25139f78bc947a68366213902a31ae350/packages/firebase_ui_auth/lib/src/screens/email_verification_screen.dart#L199) in the email verification screen. I experimented a little and added some new labels but it turned out that it does not handle if new label definitions are missing from existing localizations. I could create another PR for that, but what is your suggestion, how to handle the different localizations? Should I add these in English to every arb?

2022-12-16 12:32 UTC, lesnitsky commented
@koltai75 no need to assign, @Kukkerem feel free to review this PR

as of hardcoded labels – we're looking into adding translations to those early next year, so no action required from you.

2023-01-06 13:06 UTC, lesnitsky commented
@koltai75, seems like @Kukkerem is not responsive, do you know someone else who speaks Hungarian and could review this PR?

2023-01-07 08:23 UTC, Kukkerem requested changes
I have only found a few small things, but all in all, excellent work!

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +  String get mfaTitle => "2 lépcsős ellenőrzés";
Kétlépcsős/Kétlépéses azonosítás/ellenőrzés/hitelesítés

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "mfaTitle": "2 lépcsős ellenőrzés",
Kétlépcsős/Kétlépéses azonosítás/ellenőrzés/hitelesítés

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +  String get nullLabel => "nulla";
Ez lehetne inkább "null érték".

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "nullLabel": "nulla",
Ez lehetne inkább "null érték".

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "passwordResetEmailSentText": "Küldtünk egy levelet a jelszó visszaállításához. Kérjük, ellenőrizze a postaládáját!",
Levelet helyett talán "e-mailt"?

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +      "Küldtünk egy levelet a varázs hivatkozással. Kérjük, ellenőrizze a postaládáját és kattintson a hivatkozásra a belépéshez!";
Levelet helyett talán "e-mailt"? A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "signInWithEmailLinkSentText": "Küldtünk egy levelet a varázs hivatkozással. Kérjük, ellenőrizze a postaládáját és kattintson a hivatkozásra a belépéshez!",
Levelet helyett talán "e-mailt"? A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "sendLinkButtonLabel": "Varázs hivatkozás küldése",
A "Belépési link" jobban hangzana.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "signInWithEmailLinkViewTitleText": "Belépés varázs hivatkozással",
A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +  String get emailLinkSignInButtonLabel => "Belépés varázs hivatkozással";
A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +  String get sendLinkButtonLabel => "Varázs hivatkozás küldése";
A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +  String get signInWithEmailLinkViewTitleText => "Belépés varázs hivatkozással";
A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/src/lang/hu.dart
> +      "Küldtünk egy levelet a jelszó visszaállításához. Kérjük, ellenőrizze a postaládáját!";
Levelet helyett talán "e-mailt"?

2023-01-07 08:23 UTC, Kukkerem commented on packages/firebase_ui_localizations/lib/l10n/firebase_ui_hu.arb
> +  "emailLinkSignInButtonLabel": "Belépés varázs hivatkozással",
A "Belépési link" jobban hangzana varázs hivatkozás helyett.

2023-01-07 09:08 UTC, koltai75 commented
@lesnitsky I changed some localization texts according to the suggestions of @Kukkerem.

2023-01-07 09:12 UTC, Kukkerem approved these changes
It seems perfect!

2023-01-12 11:08 UTC, pr-Mais approved these changes

2023-01-12 11:09 UTC, Lyokone approved these changes

2023-01-12 11:09 UTC, merged