Added Hebrew language to firebase_ui_localizations
firebase/flutterfire pull request #10300
Opened 2023-01-19 15:51 UTC by beyondeye

## Description

Added Hebrew language to firebase_ui_localizations

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ x] All existing and new tests are passing.
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide].
- [ x] I signed the [CLA].
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x ] No, this is *not* a breaking change.

2023-01-30 12:29 UTC, russellwheatley commented
Hey @beyondeye, do you mind having the translations checked over by someone else who speaks Hebrew with an approval, please? Perhaps a friend/colleague on GitHub? Unfortunately, no maintainers speak Hebrew.

2023-01-30 12:47 UTC, beyondeye commented
Hi @russellwheatley. I speak Hebrew myself; I can search also for somebody else for a double check, do you have any specific requirement for the person I should that should check the translation?

2023-01-30 16:54 UTC, beyondeye commented
@russellwheatley . So once I have somebody proofread all the translations what will be the procedure next? should I communicate his/her GitHub handle and you will give them authorization  to approve the pull request?

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "התחברות באמצעות חשבון משתמש Apple"; //"Sign in with Apple";
In this line and other lines
I prefer account as חשבון and not as חשבון משתמש

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +  String get signOutButtonText => "התנתקות"; //"Sign out";
התנתק

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "הבאת קוד SMS באופן אוטומטי נכשלה. אנא הזן את הקוד שלך באופן ידני"; //"Failed to resolve SMS code automatically. Please enter your code manually";
Seems like you have double space.
I'd use ייבוא and not הבאת

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "אימות קוד SMS..."; //"Verifying SMS code…";
מאמת קוד SMS...

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +  String get confirmPasswordInputLabel => "אשר סיסמה"; // "Confirm password";
וודאי סיסמה?

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "אשר את הסיסמה שלך"; //"Confirm your password";
וודא את הסיסמה שלך?

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +  String get goBackButtonLabel => "חזרה למסך הקודם"; //"Go back";
חזרה
In the next translation you only wrote - הבא

2023-02-05 05:26 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +  String get profile => "פרופיל משתמש"; //"Profile";
פרופיל will be enough

2023-02-06 14:19 UTC, russellwheatley commented
Thanks for the input @lironhl 😄. What do you think, @beyondeye?

2023-02-06 14:47 UTC, beyondeye commented
@lironhl Thanks a lot! I have committed all the fixes.

2023-02-06 18:36 UTC, lironhl requested changes
Sorry, but couple of comments and you're good to go

2023-02-06 18:36 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "וודא הסיסמה שלך"; //"Confirm your password";
וודא את הסיסמה שלך

2023-02-06 18:36 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "היכנס באמצעות חשבון בטוויטר"; //"Sign in with Twitter";
כניסה באמצעות חשבון טוויטר 
Like the others

2023-02-06 18:36 UTC, lironhl commented on packages/firebase_ui_localizations/lib/src/lang/he.dart
> +      "ייבוא קוד SMS באופן אוטומטי נכשלה. אנא הזן את הקוד שלך באופן ידני"; //"Failed to resolve SMS code automatically. Please enter your code manually";
ייבוא קוד ה-SMS באופן אוטומטי נכשל. אנא הזן את הקוד שלך באופן ידני

2023-02-06 21:58 UTC, beyondeye commented
@lironhl Again thank you. I hope that now we hunted down all the errors.

2023-02-07 04:31 UTC, lironhl approved these changes

2023-02-07 16:17 UTC, lironhl approved these changes

2023-02-09 10:18 UTC, russellwheatley approved these changes

2023-02-09 10:21 UTC, lesnitsky approved these changes

2023-02-09 12:28 UTC, merged