[cloud_firestore] startAfterDocument with where a DocumentReference throws
firebase/flutterfire pull request #10339
Opened 2023-01-27 18:59 UTC by agent3bood

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

[*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*](https://github.com/firebase/flutterfire/issues/10338)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

The command `melos run analyze` fails in packages not related to my PR, see bellow.
```
$ melos exec
  └> dart analyze . --fatal-infos
     └> FAILED (in 4 packages)
        └> cloud_firestore_odm (with exit code 1)
        └> cloud_firestore_odm_example (with exit code 1)
        └> cloud_firestore_odm_generator (with exit code 1)
        └> cloud_firestore_odm_generator_integration_test (with exit code 1)

```

2023-01-30 08:26 UTC, Lyokone requested changes
Looks good but tests should be moved to integration testing.

2023-01-30 08:26 UTC, Lyokone commented on packages/cloud_firestore/cloud_firestore/test/query_test.dart
> +      });
Could you move this test to the integration tests: `packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart`? So you don't need to mock the channel and we can check it works on a real device.

2023-02-02 09:35 UTC, Lyokone approved these changes

2023-02-02 09:55 UTC, Lyokone commented
Rebased the branch on master to get CI working with Flutter 3.7

2023-02-02 13:28 UTC, russellwheatley approved these changes

2023-02-02 13:32 UTC, merged

2023-02-02 13:32 UTC, Lyokone commented
Thanks for your help :)