Update crashlytics docs
firebase/flutterfire pull request #10772
Opened 2023-04-11 12:26 UTC by K9i-0

## Description

This PR updates the documentation to clarify error handling and exception reporting with FirebaseCrashlytics in Flutter applications. The changes aim to provide clearer instructions for developers integrating FirebaseCrashlytics.

- Remnants from using runZonedGuarded made it unnatural

- Changed the expression based on the example

## Related Issues

None. This PR is not related to any existing issues from the issue database.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-04-25 13:40 UTC, russellwheatley requested changes

2023-04-28 06:08 UTC, K9i-0 commented on docs/crashlytics/_customize-crash-reports.md
> +    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
I have updated it.
[4c74317](https://github.com/firebase/flutterfire/pull/10772/commits/4c74317d2e55c512cafb145c6cd0ae6d55bb729b)

2023-06-08 08:54 UTC, russellwheatley commented
@kevinthecheung - we've made some changes to Crashlytics documentation if you could give it a review, that would be great. Thanks.

2023-06-12 17:05 UTC, rachelsaunders commented on docs/crashlytics/_customize-crash-reports.md
> +    // If you wish to record a "non-fatal" exception, please use `FirebaseCrashlytics.instance.recordFlutterError` instead
Throughout --

1) pls change "wish" to "want"
2) pls remove the word "please" (we don't use "please" in our tech docs)

2023-06-13 08:32 UTC, russellwheatley commented
@K9i-0 - do you mind changing the above mentioned by @rachelsaunders & @mrober, please? We can get this PR merged once done. Thanks.

2023-07-13 10:21 UTC, russellwheatley commented
Closing in favour of: https://github.com/firebase/flutterfire/pull/11275

2023-07-13 10:21 UTC, closed without merging