docs: Fixing main `README.md` broken link for `flutterfire_ui`
firebase/flutterfire pull request #10787
Opened 2023-04-13 22:51 UTC by cgalo

## Description
Removed reference to `flutterfire_ui` directory, and added list of UI related packages  (per [comment](https://github.com/firebase/flutterfire/pull/10509#pullrequestreview-1315474381)).

## Related Issues
This pull request resolves #10459 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-04-13 23:10 UTC, cgalo commented
Hi @russellwheatley, I saw your comment on this stale [PR ](https://github.com/firebase/flutterfire/pull/10509). I tried addressing your [comment ](https://github.com/firebase/flutterfire/pull/10509#pullrequestreview-1315474381). If you could please review this change and let me know if there are any additional `ui` packages you would want me to reference.

2023-04-14 11:39 UTC, lesnitsky requested changes

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +- FlutterFire UIs (beta)
```suggestion
- Firebase UI
```

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +  - [Auth UI](./packages/firebase_ui_auth/README.md)
```suggestion
  - [Firebase UI for Authentication](./packages/firebase_ui_auth/README.md)
```

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +  - [Database UI](./packages/firebase_ui_database/README.md)
```suggestion
  - [Firebase UI for Realtime Database](./packages/firebase_ui_database/README.md)
```

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +  - [Firestore UI](./packages/firebase_ui_firestore/README.md)
```suggestion
  - [Firebase UI for Cloud Firestore](./packages/firebase_ui_firestore/README.md)
```

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +  - [OAuth UI](./packages/firebase_ui_oauth/README.md)
```suggestion
```

2023-04-14 11:39 UTC, lesnitsky commented on README.md
> +  - [OAuth UI](./packages/firebase_ui_oauth/README.md)
this one is rarely used directly and there are notes on `firebase_ui_auth` about `firebase_ui_oauth` installation

2023-04-25 12:39 UTC, russellwheatley approved these changes

2023-04-25 12:39 UTC, merged