[cloud_firestore_odm_generator] Support all iterables, not just lists
firebase/flutterfire pull request #11361
Opened 2023-07-24 14:22 UTC by Rexios80

## Description

Support generating query methods for all iterables, not just lists

## Related Issues

#11344

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-07-27 09:42 UTC, rrousselGit commented on packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
> +        type.isPrimitiveIterable ||
We don't want to allow any Iterable. Iterables may have an infinite length. 

We only want fixed-length collections. Such as List/Set

2023-07-27 09:45 UTC, rrousselGit commented
This would need testing.

2023-07-31 09:47 UTC, rrousselGit commented
This still needs testing. Could you add tests? :)

2023-07-31 09:47 UTC, rrousselGit requested changes
This still needs testing. Could you add tests? :)

2023-07-31 09:50 UTC, rrousselGit commented
Sorry I might have not been specific enough as I just saw you added some things in the integration folder

In this specific scenario, we'll want to test that the generated code is correct. So we'll want a few tests that run a query using what's newly generated

2023-08-16 08:04 UTC, rrousselGit commented on packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
> +        type.isPrimitiveIterable ||
```suggestion
        type.isSupportedPrimitiveIterable ||
```

2023-08-16 08:04 UTC, rrousselGit commented on packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
> +  bool get isPrimitiveIterable {
```suggestion
  bool get isSupportedPrimitiveIterable {
```

2023-08-16 08:05 UTC, rrousselGit approved these changes
This is looking good! Thanks for this :)

2023-08-16 08:07 UTC, Lyokone approved these changes

2023-08-16 08:31 UTC, merged