fix(firebase_auth): Fix `PlatformException` to `FirebaseAuthException…
firebase/flutterfire pull request #11533
Opened 2023-08-31 14:34 UTC by Isti01

## Description

The message field of `FirebaseAuthException` contains broken JSON when receiving `BLOCKING_FUNCTION_ERROR_RESPONSE`
see (https://github.com/firebase/flutterfire/issues/11532)

## Related Issues

Fixes: firebase/flutterfire#11532

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-09-01 10:33 UTC, russellwheatley requested changes
LGTM - just made a note suggestion

2023-09-01 10:33 UTC, russellwheatley commented on packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
> +    }
```suggestion
    if (parsedMessage?.endsWith(' ]') ?? false) {
    	// Fixes JSON response from Auth blocking function: https://github.com/firebase/flutterfire/issues/11532
      parsedMessage = parsedMessage!.substring(0, parsedMessage.length - 2);
    }
```

2023-09-01 10:38 UTC, russellwheatley commented
FYI; I was able to reproduce this when I implemented a blocking function:
<img width="266" alt="Screenshot 2023-09-01 at 10 49 49" src="https://github.com/firebase/flutterfire/assets/16018629/4ad5d18b-fd22-415d-9d38-3ce22ce65869">

2023-09-05 12:51 UTC, russellwheatley commented
You need to run `melos run format` in the project to fix formatting CI. Install melos by running:
```
dart pub global activate melos
```

2023-09-05 17:43 UTC, Isti01 commented
Formatted the file, thanks!

2023-09-12 11:05 UTC, Isti01 commented
@russellwheatley Could you check again, please?

2024-01-08 13:37 UTC, russellwheatley commented
Hey @Isti01 - sorry about the delay. do you mind resolving the conflicts and we can look to get this approved/merged? Thanks.

2024-01-08 14:14 UTC, Isti01 commented
Hey @russellwheatley, I resolved the conflicts

2024-01-08 16:19 UTC, Isti01 commented
Hi! @russellwheatley! I addressed the changes you requested but the merging is still blocked due to an unadressed change request, which is weird. Is that an issue?

2024-01-08 16:40 UTC, russellwheatley approved these changes

2024-01-08 17:19 UTC, exaby73 approved these changes

2024-01-09 07:40 UTC, merged