fix(core, apple): remove usage of deprecated options trackingID and androidClientID
firebase/flutterfire pull request #11893
Opened 2023-11-15 13:06 UTC by Lyokone

## Description

As mentioned in the reference docs, those parameters are unused by the SDK:
https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIROptions#trackingid

## Related Issues

closes #11751 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-11-16 14:20 UTC, russellwheatley approved these changes

2023-11-16 14:22 UTC, russellwheatley requested changes
you will have to update the tests for this I believe. I think there are deprecated property changes on android as well 🤔

2023-11-16 15:29 UTC, Lyokone commented
@russellwheatley, I thought it was saved in the Dart part, it's fixed :)

2023-11-17 08:47 UTC, russellwheatley approved these changes

2023-11-17 09:13 UTC, merged