feat(firestore, web): migrate web to js_interop to be compatible with WASM
firebase/flutterfire pull request #12169
Opened 2024-01-17 14:02 UTC by Lyokone

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

https://github.com/firebase/flutterfire/issues/12027

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-01-22 22:06 UTC, exaby73 approved these changes

2024-01-23 09:05 UTC, russellwheatley requested changes
Left a small comment but LGTM

2024-01-23 12:02 UTC, Lyokone commented on packages/cloud_firestore/cloud_firestore/example/lib/main.dart
> +  );
Yes it was definitely something that I forgot to move :) Thanks for noticing

2024-01-24 12:50 UTC, merged

2024-02-15 21:55 UTC, IchordeDionysos commented on packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
@Lyokone is there a reason that `js` is still listed as dependency, or was this just missed in the PR?

There seem to be no more usages here:
https://github.com/search?q=repo%3Afirebase%2Fflutterfire+path%3A%2F%5Epackages%5C%2Fcloud_firestore%5C%2F%2F+dart%3Ajs&type=code