fix(storage): properly allow a null SttableMetadata object to native
firebase/flutterfire pull request #12373
Opened 2024-02-22 13:18 UTC by Lyokone

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

closes #12363 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-02-22 14:58 UTC, exaby73 approved these changes

2024-02-22 15:12 UTC, russellwheatley requested changes
Can we test this? i.e upload file without metadata and download + check it has correct metadata set?

2024-02-22 15:12 UTC, russellwheatley commented on packages/firebase_storage/firebase_storage/example/lib/main.dart
> +    // final metadata = SettableMetadata(
Maybe reinstate this

2024-02-22 15:16 UTC, Lyokone commented on packages/firebase_storage/firebase_storage/example/lib/main.dart
> +    // final metadata = SettableMetadata(
Reinstated :)

2024-05-13 10:36 UTC, russellwheatley commented
Closing out as we have already merged a solution to this issue 🙏

2024-05-13 10:36 UTC, closed without merging