Removed duplicates; fixed typos; removed "unnecessary use of a null check"
firebase/flutterfire pull request #16815
Opened 2024-12-03 19:19 UTC by Nikita0x

## Description

Docs:
Fixing typos, removing duplicates

Code:
Removed the "unnecessary use of a null check". Actually, it wasn't me but a compiler forced me to do it!

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-12-11 08:00 UTC, Nikita0x commented
I am not sure why some tests failed to be honest. I would like a help from somebody, I just changed the text in the docs mostly

2025-01-06 11:08 UTC, russellwheatley requested changes

2025-01-06 11:08 UTC, russellwheatley commented on packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
> +      return User._(this, _delegate.currentUser);
Remove this change. See analyser CI: https://github.com/firebase/flutterfire/actions/runs/12146687849/job/34223264511?pr=16815#step:5:126

2025-01-06 12:36 UTC, Nikita0x commented on packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
> +      return User._(this, _delegate.currentUser);
@russellwheatley done

2025-05-13 13:53 UTC, russellwheatley requested changes
last couple of bits and we can get this in

2025-05-13 13:53 UTC, russellwheatley commented on packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
> -  ///    email/password accounts in the Firebase Console, under the Auth tab.
I think this should be reinstated.

2025-05-13 14:08 UTC, Nikita0x commented on packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
> -  ///    email/password accounts in the Firebase Console, under the Auth tab.
reinstated

2025-05-13 14:08 UTC, Nikita0x commented on packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
> -  ///    email/password accounts in the Firebase Console, under the Auth tab.
reinstated

2025-05-13 14:10 UTC, Nikita0x commented
sorry, idk what I was thinking, those are clearly not duplicates 😰😰

2025-05-13 15:29 UTC, russellwheatley approved these changes

2025-05-13 15:31 UTC, merged