Small Typo in function documentation of createUserWithEmailAndPassword
firebase/flutterfire pull request #16866
Opened 2024-12-12 10:23 UTC by JaFeKl

just a small typo I came across while checking the function documentation

2024-12-12 11:05 UTC, SelaseKay commented
Hi @JaFeKl, thanks for the fix. Kindly sign the CLA.

2024-12-17 11:40 UTC, russellwheatley requested changes

2024-12-17 11:40 UTC, russellwheatley commented on packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
>    ///  - Thrown if there was a network request error, for example the user don't
```suggestion
  ///  - Thrown if there was a network request error, for example, if the user doesn't
```

2024-12-17 11:41 UTC, russellwheatley commented on packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
>    ///  - Thrown if there was a network request error, for example the user don't
@JaFeKl - also still saying CLA hasn't been signed 🤔

2025-05-13 13:54 UTC, russellwheatley commented
Covered in this PR: https://github.com/firebase/flutterfire/pull/16815

2025-05-13 13:54 UTC, closed without merging