chore(ui): add necessary labels
firebase/flutterfire pull request #8366
Opened 2022-03-31 11:46 UTC by lesnitsky

## Description

This PR adds new labels to the localization classes

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-03-31 11:53 UTC, lesnitsky commented
Hi @adityathakurxd @bazookon @pr-Mais @bgoktugozdemir @KikiManjaro @alexodus @makumaaku @kmartins @renefloor 
@ekasetiawans @mkoehne!

You were original authors of localization PRs, could you please have a look at these new labels and add translations for your language?

2022-03-31 12:58 UTC, remonh87 commented on packages/flutterfire_ui/lib/src/i10n/lang/nl.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
> Suggested change 
>     this.verifyEmailTitleText = 'Verify your email',
>     this.emailVerificationInstructionText =
>         'A verification email has been sent to your email address. '
>             'Please check your email and click on the link to verify '
>             'your email address.',
>     this.couldntVerifyEmailText = "We couldn't verify your email address. ",
>     this.resendVerificationEmailButtonLabel = 'Resend verification email',
>     this.verifyEmailTitleText = 'Verifieer uw e-mailadres',
>     this.emailVerificationInstructionText =
>         'Een verificatie-e-mail is naar uw e-mailadres gestuurd.'
>             'Controleer uw e-mail aub en klik op de link om  uw e-mailadres te verifiëren.',
>     this.couldntVerifyEmailText = 'We konden uw e-mailadres niet verifiëren.',
>     this.resendVerificationEmailButtonLabel = 'Verificatie e-mail opnieuw versturen',
@renefloor 
Looks good two small things: 
- I personally would go for verificatie e-mail. also  not convinced about `Controleer uw e-mail aub en` maybe it should become `Controlleer uw e-mail` ?
- Remove the double spaces  in `this.emailVerificationInstructionText`

2022-03-31 13:01 UTC, pr-Mais commented on packages/flutterfire_ui/lib/src/i10n/lang/ar.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.credentialAlreadyInUseErrorText =
        'المعلومات المدخلة مرتبطة مسبقاً بحساب مستخدم مختلف.',
    this.verifyEmailTitleText = 'التحقق من البريد الالكتروني',
    this.emailVerificationInstructionText =
        'تم إرسال رسالة تحقق إلى عنوان بريدك الإلكتروني. '
            '.يرجى تفقد صندوق بريدك والضغط على الرابط لإتمام عملية التحقق ',
    this.couldntVerifyEmailText = 'فشلت عملية التحقق من بريدك الالكتروني. ',
    this.resendVerificationEmailButtonLabel = 'إعادة إرسال رسالة التحقق',
```

2022-03-31 15:01 UTC, bgoktugozdemir commented
Sure, I will check it tomorrow.

2022-04-01 12:47 UTC, renefloor commented on packages/flutterfire_ui/lib/src/i10n/lang/nl.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
It is officially verificatie-e-mail I think, but I agree that the word is a bit weird.

2022-04-01 12:49 UTC, renefloor commented on packages/flutterfire_ui/lib/src/i10n/lang/nl.dart
> +        'This credential is already associated with a different user account.',
```suggestion
    this.credentialAlreadyInUseErrorText =
        'Deze inloggegevens  zijn al in gebruik voor een ander account.',
```

2022-04-01 15:38 UTC, bgoktugozdemir commented on packages/flutterfire_ui/lib/src/i10n/lang/tr.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.credentialAlreadyInUseErrorText =
        'Bu kimlik bilgisi zaten farklı bir kullanıcı hesabıyla ilişkilidir.',
    this.verifyEmailTitleText = 'E-mail adresini doğrula',
    this.emailVerificationInstructionText =
        'Doğrulama maili e-mail adresinize gönderildi. '
            "Lütfen e-mail'inizi kontrol edin ve e-mail adresinizi "
            'doğrulamak için bağlantıya tıklayın.',
    this.couldntVerifyEmailText = 'E-mail adresinizi doğrulayamadık.',
    this.resendVerificationEmailButtonLabel = 'Doğrulama mailini yeniden gönder',
```

2022-04-01 15:38 UTC, bgoktugozdemir commented on packages/flutterfire_ui/lib/src/i10n/lang/en.dart
> +    this.couldntVerifyEmailText = "We couldn't verify your email address. ",
There is an extra space here. Is it correct? I deleted it in the Turkish localization file.

2022-04-03 23:57 UTC, makumaaku commented on packages/flutterfire_ui/lib/src/i10n/lang/ja.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.credentialAlreadyInUseErrorText =
        '認証情報が他のアカウントと紐づいています。',
    this.verifyEmailTitleText = 'メールアドレスの認証',
    this.emailVerificationInstructionText =
        'メールアドレスに認証メールが送信されました。'
            'メールをご確認の上、リンクをクリックし、認証を行ってください。',
    this.couldntVerifyEmailText = "メールの認証に失敗しました ",
    this.resendVerificationEmailButtonLabel = '認証メールを再送する',
```

2022-04-04 14:04 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +        'This credential is already associated with a different user account.',
```suggestion
        'Kredensial ini telah digunakan oleh akun lain.',
```

2022-04-04 14:05 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +        'A verification email has been sent to your email address. '
```suggestion
        'Surat verifikasi telah dikirimkan ke alamat surel Anda. '
```

2022-04-04 14:06 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +            'Please check your email and click on the link to verify '
```suggestion
            'Silakan periksa surel Anda dan klik tautan untuk melakukan verifikasi '
```

2022-04-04 14:07 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +            'your email address.',
```suggestion
            'alamat surel Anda.',
```

2022-04-04 14:07 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +    this.couldntVerifyEmailText = "We couldn't verify your email address. ",
```suggestion
    this.couldntVerifyEmailText = "Kami tidak dapat memverifikasi alamat surel Anda. ",
```

2022-04-04 14:08 UTC, ekasetiawans commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.resendVerificationEmailButtonLabel = 'Kirim ulang verifikasi surel',
```

2022-04-04 14:10 UTC, ekasetiawans requested changes
I did it

2022-04-05 08:09 UTC, Code-Remote commented on packages/flutterfire_ui/lib/src/i10n/lang/nl.dart
> +        'Een verificatie e-mail is naar uw e-mailadres gestuurd. '
In other text I see the use of 'je' instead of 'uw'  (see `signInWithEmailLinkSentText` maybe change that line too?)

2022-04-05 09:22 UTC, renefloor commented on packages/flutterfire_ui/lib/src/i10n/lang/nl.dart
> +        'Deze inloggegevens  zijn al in gebruik voor een ander account.',
```suggestion
        'Deze inloggegevens zijn al in gebruik voor een ander account.',
```

2022-04-15 13:15 UTC, KikiManjaro commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.credentialAlreadyInUseErrorText =
        'Ces informations sont déjà associées à un autre compte.',
    this.verifyEmailTitleText = 'Veuillez vérifier votre adresse email',
    this.emailVerificationInstructionText =
        'Un mail de vérification vous a été envoyé. '
            'Veuillez examiner vos emails et cliquer sur le lien pour vérifier '
            'votre adresse email.',
    this.couldntVerifyEmailText = "Nous n'avons pas réussi à vérifier votre adresse email. ",
    this.resendVerificationEmailButtonLabel = 'Renvoyer un mail de vérification',
```

2022-04-21 14:10 UTC, mkoehne reviewed
German translation

2022-04-21 14:10 UTC, mkoehne commented on packages/flutterfire_ui/lib/src/i10n/lang/de.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
this.credentialAlreadyInUseErrorText =
        'Diese Anmeldedaten werden bereits für ein anderes Konto verwendet.',
    this.verifyEmailTitleText = 'Bestätigen Sie Ihre E-Mail',
    this.emailVerificationInstructionText =
        'Es wurde eine Bestätigungs-E-Mail an Ihre E-Mail-Adresse gesendet. Bitte prüfen Sie Ihre E-Mail und klicken Sie auf den Link, um Ihre E-Mail-Adresse zu bestätigen.',
    this.couldntVerifyEmailText =
        'Wir konnten Ihre E-Mail-Adresse nicht verifizieren.',
    this.resendVerificationEmailButtonLabel =
        'Bestätigungs-E-Mail erneut senden',

2022-04-21 20:09 UTC, mkoehne reviewed
German translation

2022-04-21 20:09 UTC, mkoehne commented on packages/flutterfire_ui/lib/src/i10n/lang/de.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.credentialAlreadyInUseErrorText =
'Diese Anmeldedaten werden bereits für ein anderes Konto verwendet.',
this.verifyEmailTitleText = 'Bestätigen Sie Ihre E-Mail',
this.emailVerificationInstructionText =
'Es wurde eine Bestätigungs-E-Mail an Ihre E-Mail-Adresse gesendet. Bitte prüfen Sie Ihre E-Mail und klicken Sie auf den Link, um Ihre E-Mail-Adresse zu bestätigen.',
this.couldntVerifyEmailText =
'Wir konnten Ihre E-Mail-Adresse nicht verifizieren.',
this.resendVerificationEmailButtonLabel =
'Bestätigungs-E-Mail erneut senden',
```

2022-04-21 21:52 UTC, polilluminato commented
I made the Italian translation in the pull request https://github.com/firebase/flutterfire/pull/8500

2022-04-23 03:50 UTC, ephelsa requested changes
Spanish translation 😁

2022-04-23 03:50 UTC, ephelsa commented on packages/flutterfire_ui/lib/src/i10n/lang/es.dart
> +        'This credential is already associated with a different user account.',
```suggestion
        'Esta credencial ya se encuentra asociada a un usuario diferente.',
```

2022-04-23 03:50 UTC, ephelsa commented on packages/flutterfire_ui/lib/src/i10n/lang/es.dart
> +    this.verifyEmailTitleText = 'Verify your email',
```suggestion
    this.verifyEmailTitleText = 'Verifica tu correo electrónico',
```

2022-04-23 03:50 UTC, ephelsa commented on packages/flutterfire_ui/lib/src/i10n/lang/es.dart
> +            'your email address.',
```suggestion
        'Un mensaje de verificación ha sido enviado a tu dirección de correo electrónico. '
            'Por favor, revisa tu correo electrónico y clica en el link para realizar la verificación '
            'tu dirección de correo electrónico.',
```

2022-04-23 03:50 UTC, ephelsa commented on packages/flutterfire_ui/lib/src/i10n/lang/es.dart
> +    this.couldntVerifyEmailText = "We couldn't verify your email address. ",
```suggestion
    this.couldntVerifyEmailText = "No pudimos verificar tu correo electrónico. ",
```

2022-04-23 03:50 UTC, ephelsa commented on packages/flutterfire_ui/lib/src/i10n/lang/es.dart
> +    this.resendVerificationEmailButtonLabel = 'Resend verification email',
```suggestion
    this.resendVerificationEmailButtonLabel = 'Reenviar correo de verificación',
```

2022-07-15 19:51 UTC, grlduarte commented
Hey @lesnitsky, as for now there's no internationalization for the `weak-password` error, do you plan to include it in this PR? If you do I can help with translation for Portuguese

2022-07-19 12:40 UTC, grlduarte commented on packages/flutterfire_ui/lib/src/auth/widgets/error_text.dart
```suggestion
case 'weak-password':
  return labels.weakPasswordErrorText;
```

2022-07-23 14:52 UTC, KikiManjaro approved these changes
Seems good for french translation

2022-08-09 17:56 UTC, closed without merging