fix: flutterfire_ui README links
firebase/flutterfire pull request #8630
Opened 2022-05-10 20:16 UTC by pedrobalao

## Description

The flutterfire_ui README file had some links broken, as they were pointing to a 'docs' folder instead of 'doc'. This PR intends to fix it. 

## Related Issues

#8628

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [*] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [NA] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [NA] All existing and new tests are passing.
- [NA] I updated/added relevant documentation (doc comments with `///`).
- [NA] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [*] I read and followed the [Flutter Style Guide].
- [*] I signed the [CLA].
- [*] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [*] No, this is *not* a breaking change.

2022-05-10 21:54 UTC, kevinthecheung requested changes
One more on line 58 ("Learn more in the Integrating your first screen section...").

2022-05-10 21:54 UTC, kevinthecheung commented
Thanks!

2022-05-11 16:02 UTC, kevinthecheung approved these changes

2022-05-12 20:37 UTC, Salakar approved these changes

2022-05-12 20:37 UTC, merged