feat(firebase_analytics): add appInstanceId property
firebase/flutterfire pull request #8689
Opened 2022-05-16 06:34 UTC by willbryant

Add an appInstanceId property on FirebaseAnalytics, exporting the API from the underlying native Firebase library implementations.

## Description

This value is needed to send server-side events through the Measurement Protocol as a part of the same session, and also useful for debugging to pair up with the data visible in DebugView and BigQuery.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-05-18 09:45 UTC, russellwheatley requested changes
Hey @willbryant, nice work! Couple of things I'd like to see, please:

1. Could you add another mock test for the platform interface [here](packages/firebase_analytics/firebase_analytics_platform_interface/test/mock.dart)?
2. Do you mind updating the java implementation to use the [TaskCompletionSource](https://github.com/firebase/flutterfire/pull/8583/files#diff-3b0d151d53818c29df4db13f383f4b7291d7bdaf3f31425125e4c2c09c9a4a95R152-R171) like 
 the example linked?

Thanks! 😄

2022-05-18 23:40 UTC, willbryant commented
Thanks for the code review @russellwheatley!

I'll wait till your PR is merged and rebase, so I don't create a merge conflict.

Just to understand the second point, do we still need to use a TaskCompletionSource when we already have a Task? I think I'd need to Tasks.await to get the value out of that Task to pass to taskCompletionSource.setResult?

2022-05-19 09:43 UTC, russellwheatley commented
> Thanks for the code review @russellwheatley!
> 
> I'll wait till your PR is merged and rebase, so I don't create a merge conflict.
> 
> Just to understand the second point, do we still need to use a TaskCompletionSource when we already have a Task? I think I'd need to Tasks.await to get the value out of that Task to pass to taskCompletionSource.setResult?

@willbryant, yes, for consistency and to use the `cachedThreadPool` . You can do the following:

```java
taskCompletionSource.setResult(Tasks.await(analytics.getAppInstanceId()));
```

2022-05-19 09:45 UTC, willbryant commented
Cool, that's basically what I did.

I added a try/finally for consistency with the others.

2022-05-23 10:59 UTC, russellwheatley requested changes

2022-05-23 10:59 UTC, russellwheatley commented on packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
> +            taskCompletionSource.setResult(null);
```suggestion
            taskCompletionSource.setException(e);
```

2022-05-31 09:36 UTC, russellwheatley requested changes
Hey @willbryant, do you mind also updating analytics web so that it throws [this exception](https://github.com/firebase/flutterfire/blob/master/packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart#L81), please?

2022-06-05 04:42 UTC, willbryant commented
Done, and squashed.

2022-06-16 13:29 UTC, russellwheatley commented
Hey @willbryant, do you mind also adding an [e2e test](https://github.com/firebase/flutterfire/blob/master/tests/test_driver/firebase_analytics/firebase_analytics_e2e.dart) to analytics if possible? 😄

2022-07-15 08:14 UTC, willbryant commented
@russellwheatley I can't get e2e tests to run for the life of me, but I've pushed a draft, if you wouldn't mind approving a CI run.

2022-07-21 09:59 UTC, willbryant commented
Struggling a bit without CI access, can't get the main e2e test directory to run locally. But, I discovered there's a sort of second copy under example/ in the plugin itself, which showed the same issue, so using that I made a bit more progress.

Hopefully the next run works better.

2022-07-21 12:02 UTC, russellwheatley commented
@willbryant run `melos run format` and all should be well. Tip for future: comment out all e2e tests [here](https://github.com/firebase/flutterfire/blob/ea03c6b349ccd63317f96e37c85daf7e11f2a28a/tests/test_driver/driver_e2e.dart#L32-L44) and run `melos run test:e2e` for testing analytics e2e (provided you've installed `melos`).

Some of the e2e's need the emulators running to work (e.g. firebase_database) so maybe that was your problem.

I'm also presuming you've ran `melos boostrap` in the project directory 😄

2022-07-21 12:04 UTC, russellwheatley commented
ahh, you'll have to run `flutter format .`in `tests/` directory. Melos doesn't pick that up at the moment 😞

2022-07-21 19:48 UTC, willbryant commented
Hopefully that's it, thanks for you help :).

2022-07-22 09:38 UTC, Lyokone approved these changes

2022-07-22 09:39 UTC, merged