[firebase_messaging] Added 'critical' to notification settings.
firebase/flutterfire pull request #9004
Opened 2022-06-30 10:34 UTC by komaxx

Enables apps to check whether the user permitted critical alerts (iOS only)

## Description

The PR adds a `critical` to `notification_settings.dart`. This informs calling apps whether the user permitted the app to trigger critical alerts, which bypass the phone's "mute" and "focus" settings. Apple only.

The according flag `criticalAlert` was already part of the native ObjectiveC code but was not yet read in Dart. Just added that part.

## Related Issues

- none

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

2022-07-11 11:00 UTC, russellwheatley requested changes
Hey @komaxx, thanks for the PR! Could you rename to "criticalAlert" to match the iOS property?

2022-07-11 11:20 UTC, komaxx commented
> Hey @komaxx, thanks for the PR! Could you rename to "criticalAlert" to match the iOS property?

Absolutely! Done :)

2022-07-19 09:32 UTC, komaxx commented
@russellwheatley If you don't mind, could you take another look?

2022-07-20 09:15 UTC, russellwheatley approved these changes

2022-07-20 09:16 UTC, merged