fix(firebase_analytics): allow `null` values for `setDefaultEventParameters()` which removes defaults. Permissible on android and iOS.
firebase/flutterfire pull request #9135
Opened 2022-07-18 09:34 UTC by ueman

## Description

As described in the linked issue, `setDefaultEventParameters` should accept `Map<String, Object?>?`.

----

In order to reset default event parameters, you should set the corresponding key to null. In order to reset all parameters, you should pass `null`.
That's what the documentation for [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setDefaultEventParameters(android.os.Bundle)) and [iOS](https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Classes/Analytics#setdefaulteventparameters_:) says.

> Android:
> Parameters to be added to the map of parameters added to every event. They will be added to the map of default event parameters, replacing any existing parameter with the same name. Valid parameter values are String, long, and double. Setting a key's value to null will clear that parameter. Passing in a null bundle will clear all parameters.

> iOS:
> Parameters to be added to the dictionary of parameters added to every event. They will be added to the dictionary of default event parameters, replacing any existing parameter with the same name. Valid parameters are String, Int, and Double. Setting a key’s value to NSNull() will clear that parameter. Passing in a nil dictionary will clear all parameters.

However, the Dart code only accepts `Map<String, Object>` according to the [docs](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/setDefaultEventParameters.html). 

Since this fixes a bug, this is not a breaking change.

## Related Issues

Fixes #9005.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-07-20 08:13 UTC, Lyokone approved these changes

2022-07-20 08:15 UTC, Lyokone approved these changes

2022-07-20 09:08 UTC, russellwheatley approved these changes

2022-07-20 09:12 UTC, russellwheatley requested changes
Do you mind adding an e2e test [here](https://github.com/firebase/flutterfire/blob/master/tests/test_driver/firebase_analytics/firebase_analytics_e2e.dart#L184) which also tests `setDefaultEventParameters()` passing a `null` value? Thanks 🙏

2022-07-21 12:13 UTC, russellwheatley approved these changes

2022-07-21 12:13 UTC, merged