feat(ui): add firebase_ui_auth and oauth providers
firebase/flutterfire pull request #9343
Opened 2022-08-11 14:41 UTC by lesnitsky

## Description

See title

## Related Issues

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-08-11 14:41 UTC, lesnitsky commented
Should be merged after #9340

2022-08-18 13:05 UTC, Lyokone approved these changes
Big PR 😅

2022-08-18 13:05 UTC, Lyokone commented on packages/firebase_ui_auth/doc/providers/universal-email-sign-in.md
> +For a full control over every phase of the authentication lifecylce you could build a stateful widget, which implements `UniversalEmailSignInListener`:
```suggestion
For a full control over every phase of the authentication lifecycle you could build a stateful widget, which implements `UniversalEmailSignInListener`:
```

2022-08-18 13:05 UTC, Lyokone commented on packages/firebase_ui_auth/doc/providers/phone.md
> +For a full control over every phase of the authentication lifecylce you could build a stateful widget, which implements `PhoneAuthController`:
```suggestion
For full control over every phase of the authentication lifecycle you could build a stateful widget, which implements `PhoneAuthController`:
```

2022-08-18 13:06 UTC, Lyokone commented
Was this PR created after merging different PR into a branch? I feel like it could gain in readability if it was separated into several commits

2022-08-18 13:53 UTC, russellwheatley requested changes

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/phone.md
> +- [EmailLinkAuthProvider](./email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
- [EmailLinkAuthProvider](./email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/phone.md
> +- [PhoneAuthProvider](./phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/universal-email-sign-in.md
> +Universal email sign in is a flow that allows to resolve connnected auth providers given an email.
```suggestion
Universal email sign in is a flow that will resolve connected auth providers with a given email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/universal-email-sign-in.md
> +If the pre-built screens don't suite the app needs, you could use a `FindProvidersForEmailView` to build your custom screen:
```suggestion
If the pre-built screens don't suit the app needs, you could use a `FindProvidersForEmailView` to build your custom screen:
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_oauth_facebook/README.md
> +Add dependency
```suggestion
Add dependencies
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_oauth_google/README.md
> +Add dependency
```suggestion
Add dependencies
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_oauth_twitter/README.md
> +Add dependency
```suggestion
Add dependencies
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/README.md
> +flutter pub global activate
```suggestion
dart pub global activate flutterfire_cli
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/README.md
> +  - [EmaiAuthProvider](./providers/email.md) - allows to register and sign in using email and password.
```suggestion
  - [EmaiAuthProvider](./providers/email.md) - allows registering and signing in using email and password.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/README.md
> +  - [EmailLinkAuthProvider](./providers/email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
  - [EmailLinkAuthProvider](./providers/email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/README.md
> +  - [PhoneAuthProvider](./providers/phone.md) - allows to register and sign in using a phone number
```suggestion
  - [PhoneAuthProvider](./providers/phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/navigation.md
> +- [EmaiAuthProvider](./providers/email.md) - allows to register and sign in using email and password.
```suggestion
- [EmaiAuthProvider](./providers/email.md) - allows registering and signing in using email and password.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/navigation.md
> +- [EmailLinkAuthProvider](./providers/email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
- [EmailLinkAuthProvider](./providers/email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/navigation.md
> +- [PhoneAuthProvider](./providers/phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./providers/phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email-link.md
> +- [EmaiAuthProvider](./email.md) - allows to register and sign in using email and password.
```suggestion
- [EmaiAuthProvider](./email.md) - allows registering and signing in using email and password.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email-link.md
> +- [PhoneAuthProvider](./phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email-verification.md
> +- [EmaiAuthProvider](./email.md) - allows to register and sign in using email and password.
```suggestion
- [EmaiAuthProvider](./email.md) - allows registering and signing in using email and password.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email-verification.md
> +- [EmailLinkAuthProvider](./email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
- [EmailLinkAuthProvider](./email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email-verification.md
> +- [PhoneAuthProvider](./phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +If a view is also not flexible enoguh, there is an `EmailForm`:
```suggestion
If a view is also not flexible enough, there is an `EmailForm`:
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +For a full control over every phase of the authentication lifecylce you could build a stateful widget, which implements `EmailAuthListener`:
```suggestion
For full control over every phase of the authentication lifecycle you could build a stateful widget, which implements `EmailAuthListener`:
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +- [EmailLinkAuthProvider](./email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
- [EmailLinkAuthProvider](./email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +- [PhoneAuthProvider](./phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/oauth.md
> +- [EmaiAuthProvider](./email.md) - allows to register and sign in using email and password.
```suggestion
- [EmaiAuthProvider](./email.md) - allows registering and signing in using email and password.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/oauth.md
> +- [EmailLinkAuthProvider](./email-link.md) - allows to register and sign in using a link sent to email.
```suggestion
- [EmailLinkAuthProvider](./email-link.md) - allows registering and signing in using a link sent to email.
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/oauth.md
> +- [PhoneAuthProvider](./phone.md) - allows to register and sign in using a phone number
```suggestion
- [PhoneAuthProvider](./phone.md) - allows registering and signing in using a phone number
```

2022-08-18 13:53 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/phone.md
> +If a view is also not flexible enoguh, there is an `PhoneInput` and `SMSCodeInput` widgets:
```suggestion
If a view is also not flexible enough, there is an `PhoneInput` and `SMSCodeInput` widgets:
```

2022-10-13 12:18 UTC, Lyokone approved these changes

2022-10-14 09:14 UTC, pr-Mais approved these changes

2022-10-14 13:26 UTC, russellwheatley requested changes

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +## Building a custom widget with AuthFlowBuilder
```suggestion
## Building a custom widget with `AuthFlowBuilder`
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/email.md
> +For full control over every phase of the authentication lifecycle you could build a stateful widget, which implements `EmailAuthListener`:
```suggestion
For full control over every phase of the authentication lifecycle, you could build a stateful widget which implements `EmailAuthListener`:
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/phone.md
> +If a view is also not flexible enough, there is an `PhoneInput` and `SMSCodeInput` widgets:
```suggestion
If a view is also not flexible enough, there are `PhoneInput` and `SMSCodeInput` widgets:
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/phone.md
> +## Building a custom widget with AuthFlowBuilder
```suggestion
## Building a custom widget with `AuthFlowBuilder`
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/providers/universal-email-sign-in.md
> +For a full control over every phase of the authentication lifecycle you could build a stateful widget, which implements `UniversalEmailSignInListener`:
```suggestion
For full control over every phase of the authentication lifecycle, you could build a stateful widget which implements `UniversalEmailSignInListener`:
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/doc/theming.md
> +For example, the `SignInScreen` widget with an email provider, wrapped in a `MaterialApp` will use the following widgets:
```suggestion
For example, the `SignInScreen` widget with an email provider wrapped in a `MaterialApp` will use the following widgets:
```

2022-10-14 13:26 UTC, russellwheatley commented on packages/firebase_ui_auth/example/test_driver/phone_verification_test.dart
> +      'allows to pick country code',
```suggestion
      'pick country code',
```

2022-10-14 14:17 UTC, lesnitsky commented on packages/firebase_ui_auth/CHANGELOG.md
> +## 0.0.1
I'm not sure how this works either. We've put this manually for the dev release.
Next release should be without `-dev.1` postfix, but rather regular `1.0.0` version.
I believe this should be done with `--graduate`.

As for actual changelog – it'd just mention a stable release and point to the migration guide in docs section.

2022-10-17 10:41 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/configs/countries.dart
> +  {'name': 'Afghanistan', 'phoneCode': '93', 'countryCode': 'AF'},
good catch. root assets folder is no longer needed. (83e5bfb9083b117192ee8dc7b62b3fcb37066a05)

2022-10-17 12:20 UTC, merged