feat(auth): add Yahoo as provider for iOS, Android and Web
firebase/flutterfire pull request #9443
Opened 2022-08-29 09:15 UTC by Lyokone

## Description

See title

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-09-06 09:56 UTC, russellwheatley requested changes

2022-09-06 09:56 UTC, russellwheatley commented on docs/auth/federated-auth.md
> +  Before you begin [configure Yahoo Login for iOS](/docs/auth/ios/yahoo-oauth#before_you_begin) and add the [custom URL schemes
```suggestion
  Before you begin, [configure Yahoo Login for iOS](/docs/auth/ios/yahoo-oauth#before_you_begin) and add the [custom URL schemes
```

2022-09-06 09:56 UTC, russellwheatley commented on docs/auth/federated-auth.md
> +is set as your Authorization callback URL in your app's settings page on your Yahoo app's config.
```suggestion
is set as your Authorization callback URL in your app's settings page on your  app's Yahoo config.
```

2022-09-06 09:56 UTC, russellwheatley commented on docs/auth/federated-auth.md
> +  Before you begin [configure Yahoo Login for Android](/docs/auth/android/yahoo-oauth#before_you_begin).
```suggestion
  Before you begin, [configure Yahoo Login for Android](/docs/auth/android/yahoo-oauth#before_you_begin).
```

2022-09-06 09:56 UTC, russellwheatley commented
Hey @kevinthecheung, do you mind reviewing the small docs changes, please?

2022-09-06 20:55 UTC, kevinthecheung approved these changes

2022-09-06 20:55 UTC, kevinthecheung commented on docs/auth/federated-auth.md
> +.
Stray period

2022-09-06 20:55 UTC, kevinthecheung commented on docs/auth/federated-auth.md
> +is set as your Authorization callback URL in your app's settings page on your app's Yahoo config.
```suggestion
is set as a redirect URI in your app's Yahoo Developer Network configuration.
```

2022-09-07 07:35 UTC, russellwheatley approved these changes

2022-09-07 07:36 UTC, merged